server:
  port: 8761
spring:
  application:
    name: discoveryservice

eureka:
    client:
        registerWithEureka: false # server ??? ????? ??? ????? Discovery? ???? ???.(???? true)
        fetchRegistry: false
        defaultZone: http://localhost:8761/eureka/
